// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC02AlleLinksanklickenTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC02AlleLinksanklicken() {
    driver.get("https://www.lotto-brandenburg.de/home");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.linkText("Newsroom")).click();
    driver.findElement(By.linkText("Lotto fördert")).click();
    driver.findElement(By.linkText("Kontakt")).click();
    driver.findElement(By.linkText("Systemschein")).click();
    driver.findElement(By.linkText("Gewinncheck")).click();
    driver.findElement(By.linkText("Zahlen und Quoten")).click();
    driver.findElement(By.linkText("Statistik")).click();
    driver.findElement(By.cssSelector(".column:nth-child(2) > .m00201--product-nav #Ebene_1")).click();
    driver.findElement(By.linkText("Eurojackpot Schein")).click();
    driver.findElement(By.cssSelector(".column:nth-child(2) > .m00201--product-nav .list-item:nth-child(2) > .link")).click();
    driver.findElement(By.cssSelector(".column:nth-child(2) > .m00201--product-nav .list-item:nth-child(3) > .link")).click();
    driver.findElement(By.cssSelector(".column:nth-child(2) > .m00201--product-nav .list-item:nth-child(4) > .link")).click();
    driver.findElement(By.cssSelector("#Ebene_1 > #Fill-1_1_")).click();
    driver.findElement(By.linkText("GlücksSpirale Schein")).click();
    driver.findElement(By.cssSelector(".column:nth-child(3) > .m00201--product-nav .list-item:nth-child(2) > .link")).click();
    driver.findElement(By.cssSelector(".column:nth-child(3) > .m00201--product-nav .list-item:nth-child(3) > .link")).click();
    driver.findElement(By.cssSelector(".column:nth-child(4) #Ebene_1")).click();
    driver.findElement(By.linkText("Keno Schein")).click();
    driver.findElement(By.cssSelector(".column:nth-child(4) .list-item:nth-child(2) > .link")).click();
    driver.findElement(By.cssSelector(".column:nth-child(4) .list-item:nth-child(3) > .link")).click();
    driver.findElement(By.cssSelector(".column:nth-child(4) .list-item:nth-child(4) > .link")).click();
    driver.findElement(By.linkText("Wir stellen uns vor")).click();
    driver.findElement(By.cssSelector(".column:nth-child(5) .list-item:nth-child(2) > .link")).click();
    driver.findElement(By.cssSelector(".column:nth-child(5) .list-item:nth-child(3) > .link")).click();
    driver.findElement(By.linkText("Jobs")).click();
    driver.findElement(By.linkText("Vertrieb")).click();
    driver.findElement(By.cssSelector(".unsorted-list:nth-child(2) > .list-item:nth-child(6) > .-inverted")).click();
    driver.findElement(By.linkText("AGB")).click();
    driver.findElement(By.linkText("Impressum")).click();
    driver.findElement(By.linkText("Datenschutz")).click();
    driver.findElement(By.linkText("Privatsphäre")).click();
    js.executeScript("window.scrollTo(0,0)");
  }
}
