// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC03KontakftanfragesendenTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC03Kontakftanfragesenden() {
    driver.get("https://www.lotto-brandenburg.de/kontakt");
    driver.manage().window().setSize(new Dimension(1710, 1107));
    driver.findElement(By.id("anrede")).click();
    {
      WebElement dropdown = driver.findElement(By.id("anrede"));
      dropdown.findElement(By.xpath("//option[. = 'Herr']")).click();
    }
    driver.findElement(By.id("firstname")).click();
    driver.findElement(By.id("firstname")).sendKeys("Maximilian");
    driver.findElement(By.id("lastname")).sendKeys("Mustermann");
    driver.findElement(By.id("email")).sendKeys("maximilian.mustermann@gmail.com");
    driver.findElement(By.id("phone")).sendKeys("030-12345678910");
    driver.findElement(By.id("subject")).sendKeys("TC Kontaktanfrage senden");
    driver.findElement(By.id("text")).sendKeys("Hallo,\\nich bin ein automatisierter Funktionstest für den TC Kontaktanfrage #01 senden. Ich wurde erstellt mit Selenium und gehöre zur Testsuite Funktionale Tests......... ");
  }
}
